### ISSUE TITLE
Missing explanation how to set phpunit path

### ISSUE THREAD

**Issue by MarkusRodler** [recca0120/vscode-phpunit#1]
Hello,

I tried to install your extension but I have no idea how to make it run?
It is installed without errors and also without output. I am having a composer package where phpunit is installed. In my case it is not the vendor Directory. It is .\bin\phpunit because it is Flow Framework Project and I have this path to the phpunit configuration file: .\Build\BuildEssentials\PhpUnit\UnitTests.xml
Here is the command I use to run it in the powershell:  
```bash
C:\Path\To\Workspace\Project> .\bin\phpunit -c .\Build\BuildEssentials\PhpUnit\UnitTests.xml .\Packages\Application\ --colors=always`
```

So my question is: How can I set the path to phpunit executable and how can i run your extension?

Thanks,

Markus

**Comment by recca0120** [comment]
I'll add set path next version

for now
it will find phpunit in system environment  path

or

```bash
C:\Path\To\Workspace\Project> .\vendor\bin\phpunit
```

**Comment by MarkusRodler** [comment]
Thanks for the quick reply and thanks for the solution :)

**Comment by recca0120** [comment]
try 0.3.0
