### ISSUE TITLE
輸出亂碼「[30;42mOK (1 test, 4 assertions)[0m」

### ISSUE THREAD

**Issue by ycs77** [recca0120/vscode-phpunit#10]
前幾天都還很正常，直到這兩天就出問題了。

點擊「Run Test」就會輸出亂碼「[30;42mOK (1 test, 4 assertions)[0m」

![vscode output](https://user-images.githubusercontent.com/38133356/48827842-2c1aa600-eda9-11e8-80f7-04e74a8e1f4a.jpg)

請問有人知道如何解決這個問題嗎?

**Comment by recca0120** [comment]
這個應該是輸出的時候 phpunit 多了  colors 的參數，我再另外處理

**Comment by recca0120** [comment]
現在應都會正常了，我加入了 strip ansi 的程式來處理這個問題

**Comment by ycs77** [comment]
感謝修復！
