### ISSUE TITLE
Relative Path does not work with tests in subfolders

### ISSUE THREAD

**Issue by MathiasWeisheit** [recca0120/vscode-phpunit#101]
Setup:
- docker
- Source in folder /webapp/src
- Tests in folder /tests/**/*Test.php
- inside the container the Source is in /app (/webapp/src == /app)

if I start a test:
[2021-09-24 11:49:12.358] [INFO] {
  title: 'PHPUnit LSP',
  command: '\\docker-compose exec -u root webserver php',
  arguments: [
    '\\app\\vendor\\bin\\phpunit',
    '--filter',
    '"/^.*::categories_can_be_retrieved.*$/"',
    'webapp\\src\\tests\\Feature\\CategoryTest.php'
  ]
}

You see the functions calls the path webapp\\src\\tests\\Feature\\CategoryTest.php witch does not exists within the container.

Can you help me?

**Comment by recca0120** [comment]
try version 3.0
