### ISSUE TITLE
No tests found in subfolder

### ISSUE THREAD

**Issue by AndreyChursin** [recca0120/vscode-phpunit#103]
I am on Windows 10 and this is my project structure:
/local/test/**/*Test.php - all my test files
/local/tests/phpunit.xml.dist - phpunit config file

"phpunit.files": "{test,tests}/**/*Test.php",
pic. http://joxi.ru/bmoN4nyc7ZqbPr

What am I doing wrong?

**Comment by recca0120** [comment]
try version 3.0, version 3.0 will scan all php files to find test case
