### ISSUE TITLE
Feature Request: Show test status while in progress

### ISSUE THREAD

**Issue by enjibby** [recca0120/vscode-phpunit#116]
My entire test suite for a project is admittedly slow at ~5-10minutes. While I have no problems with having them run from the UI, there is very little feedback until the entire suite is complete. It would be a massive improvement if I could see which tests were queued, which ones are currently running and any passes/failures/errors/etc. (even if no additional information is yet available).

**Comment by recca0120** [comment]
this problem is fixed, you can try again
