### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by pardmeister** [recca0120/vscode-phpunit#12]
Thanks for the plugin, it's very useful.

I think there was an update that happened this morning, and now I am not seeing any colours. Previously I used to get a red or green block in the gutter, the filename and the output.

VSCode Version: 1.33.1
PHPUnit Version: 7.5.8
vscode-phpunit Version: 2.0.4
![Screenshot 2019-05-03 at 09 29 14](https://user-images.githubusercontent.com/6696083/57124437-1fea3a00-6d86-11e9-9e67-fa67a3e394fd.png)

**Comment by recca0120** [comment]
![螢幕快照 2019-05-15 下午4 50 28](https://user-images.githubusercontent.com/1390554/57762182-99443e00-7731-11e9-89c3-c4ffd9254be1.png)

this is my screenshot,
it works,
maybe you can change vscode theme, and try again
