### ISSUE TITLE
phpunit.ssh setting not working

### ISSUE THREAD

**Issue by hidalgoss** [recca0120/vscode-phpunit#121]
Hi !

I used PHPUnit extension to connect to remote machine successfuly. I run tests using "Ctrl+Shift+P -> PHPUnit Test -> myTestCase" as instance. See output below.

PHPUnit 8.5.26
Runtime: PHP 7.2.24-0ubuntu0.18.04.11 with Xdebug 2.6.0
Configuration: /home/sb-0/phpunit.xml
...... 6 / 6 (100%)
Time: 31.95 seconds, Memory: 16.00 MB
OK (6 tests, 7 assertions)

But when I run test using Test Explorer, or Run in top label of test function headers, the output command executed automatically by extension ignores ssh configuration and runs directly "phpunit.php": "/usr/bin/php", command. See output below.

[INFO] {
title: 'PHPUnit LSP',
command: '/usr/bin/php',
arguments: [
'/home/sb-0/www/iats/code/resources/composer/phpunit/phpunit/phpunit',
'-v',
'-c',
'/home/sb-0/phpunit.xml',
'--filter',
'/^.::testBadgeName.$/',
'/home/sb-0/www/iats/code/module/badge/test/BadgeUnitTest.phpunit.php'
]
}

How can we use current phpunit configuration to run tests using PHPUnit Test Explorer extension?
Am I doing something wrong?

Thnaks !!
Great work!!

**Comment by recca0120** [comment]
try version 3.0
