### ISSUE TITLE
First impressions of the rebuilt package

### ISSUE THREAD

**Issue by nunoperalta** [recca0120/vscode-phpunit#130]
Thank you very much for rebuilding this package!!
A number of issues seem to be fixed, including this one (that I reported in a fork) - https://github.com/renandelmonico/vscode-phpunit/issues/13

(well, there were several random issues similar to the above - hopefully that's all resolved)

Really appreciate that 👍🏼

However, as I understand this was the first release since the full rebuild, I'd like to point out some things:

1) My set up is quite custom, so any issues I have might be due to my setup.
I basically run an "npm" script that builds the project first, and then runs phpunit under docker.

Note that I run VSCode on Windows, but the app & phpunit runs on Docker (Linux).

2) Since this version, the `args` parameter broke for me. I got it working anyway, but creating a "wrapper" cmd that resolves the issue for me:

```
@echo off
setlocal EnableDelayedExpansion

set args_all=%*
:: npm filters out "", but quotes are required for --filter
:: https://github.com/npm/npm/issues/7743
:: so we convert "" to ''
set "args=%args_all:"='%"
echo !args!

:: using !args! so "^" isn't parsed as an escape
:: wrapping into "" so that all the arguments are passed properly
C:\node\npm.cmd run build-runtests -- "!args!"
```

This is the `build-runtests` script:

```
"build-runtests": "gulp build-debug && docker-compose run --rm --entrypoint 'php' mydockercontainer /opt/tests/run_phpunit.php",
```

And then in the workspace settings:

```
"phpunit.php": "",
"phpunit.phpunit": "F:\\path\\to\\phpunit-wrapper.cmd",
```

3) Now -- on that `run_phpunit.php`, that's where I do any "magic" needed to resolve issues with the arguments.

3.1) One thing I noticed is that you're passing `--teamcity`.

Any reason you are forcing `--teamcity`?
I use `testdox="true"`, so I had to filter `--teamcity` out of the arguments, to keep the same output I want.

3.2) I also noticed that you're passing `--colors=never`

I understand why, as otherwise it looks like this with `--colors=always`:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/487079/205490174-4756ff6a-63f4-4e49-bce4-fc9b2f55e0a8.png">

Do you know if there's a way to make the "Output" window of VSCode support colors?
Otherwise, would it be possible to run this in the "Terminal" instead? https://github.com/recca0120/vscode-phpunit/issues/105

3.3) If there is any issue with the command itself, that makes PHPUnit not run at all (while I was experimenting with the workspace parameters), the `Running tests...` indicator seems to stay there forever, and the "Output" window remains fully empty:

![..](https://user-images.githubusercontent.com/487079/205490287-48a8a778-f47b-468a-983a-fafd0f8c8afb.jpg)

![..](https://user-images.githubusercontent.com/487079/205490308-e149837e-3f30-4647-9041-42b9db216876.jpg)

If possible, it would be nice to get some indication of what the problem is, or at least display somewhere what's the exact command it's trying to run.

Thank you very much once again!

**Comment by recca0120** [comment]
about issues 1, 2

this package support docker now.
configuration like this
https://github.com/recca0120/vscode-phpunit/blob/main/src/phpunit/test-runner.test.ts#L305-L311
try to use `phpunit.command` argument maybe can help you to resolve those issues.
and I will find another way to support command like `gulp build-debug && docker-compose`

issue 3.1
only --teamcity can get the test results in real-time, so it needs force --teamcity

issue 3.2
because must force --teamcity and teamcity format always without colors, so ...
but I will reformat the output in the next version, maybe it can make the output readable.

issue 3.3
maybe show running command ...

thank you for your response..

**Comment by recca0120** [comment]
hello, I publish 3.0.1, it will print command and error message.
if there are any problems, can you paste the output here?

**Comment by nunoperalta** [comment]
Thank you very much for your reply.

Points (1) and (2) were mostly informational. As long as I have a way to successfully run PHPUnit, I'm happy 😊

I think I'll continue using my CMD wrapper, because I also need to build the code first, before running Docker, so I'm happy with that solution. No worries :)


Thank you for 3.0.1.

I see the command now in the Output window:

`C:\node\node.cmd f:\Files\........\tests\NumberTest.php --filter=^.*::(testInvalidNegativeDigitFloat)( with data set .*)?$ --teamcity --colors=never`

(I ran this as a test command that should fail)

But nothing else shows, no errors at all.

And this keeps looping:

<img width="75" alt="image" src="https://user-images.githubusercontent.com/487079/205506497-c7fd6087-b0ba-47bc-8e07-1ff4fd7eb9dd.png">

There is no "node" running on my Windows.

**Comment by nunoperalta** [comment]
Thank you very much for the latest update!!

That's much better now!! (I had to enable teamcity and colors=never back, and now it's perfect!)

<img width="62" alt="image" src="https://user-images.githubusercontent.com/487079/205599800-cb38e60c-47e0-431c-aa9d-e416c1527e74.png">


I think that's all my problems resolved now. Thank you again!!!
