### ISSUE TITLE
phpunit.paths setting doesn't resolve ${workspaceFolder}

### ISSUE THREAD

**Issue by lgrandinetti** [recca0120/vscode-phpunit#133]
When I set the absolute path of the project manually, everything works as expected, but when I try to use "${workspaceFolder}" as mentioned in the documentation, the tests fail.

Here is my settings:
```
  "phpunit.command": "docker exec --workdir=/var/www/ container_name bash -c",
  "phpunit.php": "php",
  "phpunit.paths": { 
    "${workspaceFolder}": "/var/www"
  },
  "phpunit.phpunit": "vendor/bin/phpunit"
```

**Comment by recca0120** [comment]
![截圖 2022-12-08 上午12 37 23](https://user-images.githubusercontent.com/1390554/206237424-e24189d3-72f9-4f6d-8b29-2ba0098ed479.png)
can you show the output to here ?

**Comment by recca0120** [comment]
![截圖 2022-12-08 上午1 07 09](https://user-images.githubusercontent.com/1390554/206244467-89c51910-063d-413f-b467-186af65e99d1.png)
I publish a new version. try again
