### ISSUE TITLE
CLI Arguments get messed up

### ISSUE THREAD

**Issue by tobiasbhn** [recca0120/vscode-phpunit#137]
When using Phpunit command line options in the config, the generated final command is messed up. When using a config with a hyphen separated argument, the argument will be reformatted into camel case, which is not recognised by phpunit.

![image](https://user-images.githubusercontent.com/39066612/208039219-df142fe8-bd02-41cc-aa45-039c853a3ba5.png)

Notice that both variants (original and reformatted option) are present in the final command.
https://phpunit.readthedocs.io/en/9.5/textui.html#command-line-options

**Comment by recca0120** [comment]
I'll fix it later

**Comment by recca0120** [comment]
version 3.0.19 fix this issue
