### ISSUE TITLE
Output of Laravel's dd() is not shown when running test

### ISSUE THREAD

**Issue by edmassarani** [recca0120/vscode-phpunit#139]
First of all, this new version of the package is awesome and has fixed several problems I had before, so thank you very much.

Though now there is one issue with outputting things during the test. If for any reason I'm debugging stuff in the test and there is a `dd() ` in it, the output of the dd is not shown in the test console. If I run the test in the command line it shows the dd output as usual. Is this something I can fix with configuration on my side? Or is it something that needs to be added to the plugin?

**Comment by edmassarani** [comment]
Now the test doesn't fail anymore, but the output is still not shown for me.

![image](https://user-images.githubusercontent.com/24718089/208638413-b57c6509-768f-449a-9f83-7acf31fc8a51.png)

**Comment by recca0120** [comment]
hello @edmassarani.

you can try version 3.0.23 again

**Comment by edmassarani** [comment]
alright, now it shows, though the formatting is not as nice as in the console.

test output:
![image](https://user-images.githubusercontent.com/24718089/208717156-935ed232-fcc5-4a4d-a355-4ef49cc16c55.png)

console output:
![image](https://user-images.githubusercontent.com/24718089/208717251-967af701-8065-4bea-8682-62c9d1eb4878.png)
