### ISSUE TITLE
Docker exec fails with "no such file or directory: unknown" but works in terminal

### ISSUE THREAD

**Issue by cosmolux** [recca0120/vscode-phpunit#142]
My Test Explorer is not able to run tests, yet if I copy the output from PHPUnit into the terminal the test runs!

Example output:
```
docker exec -t 5d474cbfba6e /usr/local/bin/php /radar/api/vendor/bin/phpunit /radar/api/tests_PHPUnit/radar/framework/ParamTest.php '--teamcity' '--colors=never'

❌ OCI runtime exec failed: exec failed: unable to start container process: exec: "/usr/local/bin/php /radar/api/vendor/bin/phpunit /radar/api/tests_PHPUnit/radar/framework/ParamTest.php '--teamcity' '--colors=never'": stat /usr/local/bin/php /radar/api/vendor/bin/phpunit /radar/api/tests_PHPUnit/radar/framework/ParamTest.php '--teamcity' '--colors=never': no such file or directory: unknown
```
If I copy the first line that begins, "docker exec..." and paste it into my vscode terminal the tests run correctly.
My config:
```
"phpunit.command": "docker exec -t 5d474cbfba6e",
"phpunit.php": "/usr/local/bin/php",
"phpunit.phpunit": "/radar/api/vendor/bin/phpunit",
"phpunit.paths": {
    "${workspaceFolder}": "/radar/api" 
},
```
I've confirmed that all the paths used in the command stat correctly from within the container.  I'm mystified.

**Comment by helisoncavalheiro** [comment]
I have the same issue. Any updates?

**Comment by SteffenAnders** [comment]
same here

**Comment by SteffenAnders** [comment]
> set configuration like this
> 
> ```
> "phpunit.command": "docker exec -t my_container /bin/sh -c",
> "phpunit.php": "php",
> "phpunit.phpunit": "/app/vendor/bin/phpunit",
> "phpunit.paths": {
>     "${workspaceFolder}": "/app",
> }
> ```

that worked! thanks!

**Comment by helisoncavalheiro** [comment]
> set configuration like this
> 
> ```
> "phpunit.command": "docker exec -t my_container /bin/sh -c",
> "phpunit.php": "php",
> "phpunit.phpunit": "/app/vendor/bin/phpunit",
> "phpunit.paths": {
>     "${workspaceFolder}": "/app",
> }
> ```

this works for me too! thank you!

**Comment by kemalatila-kite** [comment]
It might be better if you add it to the examples. @recca0120
