### ISSUE TITLE
Doesnt support PHPUnit version 10.

### ISSUE THREAD

**Issue by msiemaszko** [recca0120/vscode-phpunit#143]
Unfortunately, the extension cannot handle PHPunit version ^10.0. With version 9.6.3 it's still perfect!
windows 11, php 8.1.13-nts-win32-vs16-x64
![image](https://user-images.githubusercontent.com/5961267/218073343-984a6c88-63bb-44b3-af88-7ebc75426c52.png)

**Comment by msiemaszko** [comment]
I think it's because of the missing quotes in the command.

**Comment by recca0120** [comment]
try 3.0.29
