### ISSUE TITLE
Support for tests with PHPUnit\Framework\Attributes\Test php Attribute

### ISSUE THREAD

**Issue by arun07as** [recca0120/vscode-phpunit#144]
So phpunit 10 has a new feature where instead of methods starting with `test` or with the `@test` docblock, methods with the `PHPUnit\Framework\Attributes\Test` attribute are also considered as test cases. Here's a [reference of the documentation regarding this](https://phpunit.readthedocs.io/en/10.0/writing-tests-for-phpunit.html#:~:text=Alternatively%2C%20you%20can%20use%20the%20PHPUnit%5CFramework%5CAttributes%5CTest%20attribute%20on%20a%20method%20to%20mark%20it%20as%20a%20test%20method.%20See%20the%20section%20on%20the%20Test%20attribute%20for%20details.)

But the plugin sadly does not support this yet, and test cases with these attributes are not shown in the test Explorer. 

When I run tests, all the tests get executed though, even though they aren't shown in the list.

As an Example, I have a class `tests\Functional\ExampleTest.php`
```php
<?php

namespace Tests\Functional;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\Test;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     */
    #[Test]
    public function hi(): void
    {
        $this->assertTrue(true);
    }
}
```
The method `hi()` has the `PHPUnit\Framework\Attributes\Test` attribute, so it is picked up by PHPUnit, but not by the explorer.
![image (2)](https://user-images.githubusercontent.com/17740186/218449944-9f33b05a-6ac9-4c01-bcd8-a12c18fcd2d4.png)

**Comment by recca0120** [comment]
try 3.0.30

**Comment by arun07as** [comment]
Great. It's now showing. Thanks for the quick update
