### ISSUE TITLE
Tests status not updating in tests explorer

### ISSUE THREAD

**Issue by Samuel-VandePut** [recca0120/vscode-phpunit#149]
Hello,

The extension works well but some tests status are not updated in the explorer.  PHPUnit is working as I can read the result in the Output window. 

![image](https://user-images.githubusercontent.com/78546003/225928536-508db9ff-3ce8-45f2-83ea-1d3f08e43220.png)

The tests file is shown with a incorrect path 'App\Http\Controllers\Auth\'.  Do you have an idea where this come from?

Thank you !

**Comment by recca0120** [comment]
could you execute `phpunit --teamcity` and paste output here?

**Comment by Josef37** [comment]
Had a similar issue with test results sometimes showing and sometimes not...

**Solution** ✨ 
Use namespaces in test files.

**Explanation attempt**
I hadn't used namespaces in my test files.
In the test view they had some other namespace I used somewhere else.
I assume the test extension now can't match the test result to the actual file. 🤔

**Comment by recca0120** [comment]
try version 3.0.33, this extension can parse test cases without namespace
