### ISSUE TITLE
phpunit.paths setting doesn't resolve path mapping

### ISSUE THREAD

**Issue by therealkris** [recca0120/vscode-phpunit#150]
I have an issue that seems very similar to https://github.com/recca0120/vscode-phpunit/issues/133, however the fix that you released is not working for me. I am using a different `phpunit.command` and the extension doesn't seem to be resolving my path mapping. My current settings look like this: 

```
 "phpunit.command": "lando",
  "phpunit.php": "php",
  "phpunit.phpunit": "/app/vendor/bin/phpunit",
  "phpunit.paths": {
    "${workspaceFolder}": "/app"
  },
  "phpunit.args": [
    "-c /app/phpunit.xml"
  ]
```
where `${workspaceFolder}` is equal to `/Users/Kris/Developer/myapp`

And the command that ends up running is `lando php /app/vendor/bin/phpunit /Users/Kris/Developer/myapp/tests/unit/ActionLogTest.php --configuration=/app/phpunit.xml --teamcity --colors=never`

What I expect to see is `lando php /app/vendor/bin/phpunit /app/tests/unit/ActionLogTest.php --configuration=/app/phpunit.xml --teamcity --colors=never`

**Comment by ntdash** [comment]
The path mappings only seems to get resolve when `phpunit.command` start with docker.
Haven't try the `ssh` configuration, but I think It might be the same.

**Comment by recca0120** [comment]
I find this example https://github.com/lando/php/tree/main/examples/8.1

try changing your configuration like this

{
    "phpunit.command": "lando ssh -s defaults -c",
}
