### ISSUE TITLE
Problem with path to the test file

### ISSUE THREAD

**Issue by onufry7** [recca0120/vscode-phpunit#156]
When running a single test, if the path to the test file contains spaces or special characters, an error occurs. For example:

`php vendor/bin/phpunit c:\open project/page/tests/Feature/AuthenticationTest.php --teamcity --colors=never`

will return the error "Test file 'c:/open' not found". 
However, if we run this command and enclose the file path in quotes, 

`php vendor/bin/phpunit "c:\open project/page/tests/Feature/AuthenticationTest.php" --teamcity --colors=never`

it will work correctly.

How to solve this problem?

**Comment by eujoaoalves** [comment]
I got the same error here.
I wasted a lot of time and I couldn't fix it

**Comment by Yousha** [comment]
I have same problem, the extension doesn't work with paths that contain SPACE
