### ISSUE TITLE
Command-line options are not recognized by phpunit

### ISSUE THREAD

**Issue by liaochao2023** [recca0120/vscode-phpunit#158]
phpunit can get options when option is before target file
`vendor/bin/phpunit --prepend=bootstrap.php Foo.php`
but  will not work as follows
`vendor/bin/phpunit Foo.php --prepend=bootstrap.php`
can you change the order in real execute command?

**Comment by jlecordier** [comment]
I don't seem to have any issue on my side, what is your version of PHPUnit ?
