### ISSUE TITLE
extension ignores phpunit configuration

### ISSUE THREAD

**Issue by opus-2** [recca0120/vscode-phpunit#16]
I have this in my vscode settings:
```
phpunit.args = [
    "--configuration tests/phpunit.xml"
];
```
The XML file doesn't get read (therefore, doesn't bootstrap and the test won't run properly), no matter what I put in that setting, be it relative to the executable or the workspace, or an absolute path. The only way to make it work is to have the file phpunit.xml in the workspace root.

It also seems to ignore the `phpunit.php` and `phpunit.phpunit` settings (executable locations) and just run whatever it wants. 
This started when the extension auto-upgraded to 2.0, I'm now running 2.0.40 and vscode 1.34.

**Comment by recca0120** [comment]
Yes, It doesn't work now. I'll make this setting to work again in few days.

**Comment by opus-2** [comment]
That's fine, thank you.

**Comment by recca0120** [comment]
Try  latest version
