### ISSUE TITLE
Editor is read-only because the file system of the file is read-only

### ISSUE THREAD

**Issue by ennorehling** [recca0120/vscode-phpunit#162]
I have a Laravel Sail project that I am developing with the source living inside WSL. VS Code runs on Windows, and opens the project files through a WSL Remote connection. I can run my PHPUnit tests from the Test Explorer, but when I click on the "Go To Test" icon next to a test, the editor opens the source in read-only mode, saying "Editor is read-only because the file system of the file is read-only" when I try to modify it. Opening the same file from my project folder in the normal Explorer view lets me edit it just fine. Why is this happening? Because that's a neat shortcut, and I want to use it.

![image](https://github.com/recca0120/vscode-phpunit/assets/629521/0c337512-c12f-4285-b7f2-24aee903d583)

Checking with a terminal, the file is owned by me and writable, and I can edit it when I open it through normal methods (via the Explorer in VS Code or in a terminal with vim).

**Comment by recca0120** [comment]
https://code.visualstudio.com/updates/v1_79#_readonly-mode

maybe set files.readonlyExclude can resolve this issue.

**Comment by ennorehling** [comment]
No difference.

**Comment by ennorehling** [comment]
It is odd and might be a clue that the button opens another editor window, even though I already have that file opened. And while the writable one's breadcrumb path at the top of the window is relative to my project, the read-only one opened by Test Explorer is relative to my filesystem root (as seen in the screenshot).

**Comment by ennorehling** [comment]
New development: When I pressed the "Refresh Tests" button at the top of Test Explorer, the problem went away. I'd never noticed that button before, the list of test was always automatically populated.
