### ISSUE TITLE
Option to Remove --teamcity Command-line Argument

### ISSUE THREAD

**Issue by heyyoudev** [recca0120/vscode-phpunit#168]
**Description:**

Hello,

I've been using the PHPUnit Test Explorer extension with VSCode and noticed that when running tests, the --teamcity command-line argument is automatically appended to the phpunit execution command. While I understand the utility of this flag for structured output, in my specific setup, I'd prefer not to use it. The resulting output contains many ##teamcity lines, which increases verbosity and takes up a considerable amount of space in the terminal. In certain scenarios, it can make it harder to quickly discern the test results.

I've attempted to find a way to remove or disable this flag through the extension's settings and VSCode's settings.json, but I haven't found a way.

**Expected Behavior:**
Provide an option within the extension's settings to enable or disable the --teamcity command-line argument when PHPUnit tests are executed.

**Actual Behavior:**
Currently, the --teamcity flag is always appended, and there doesn't seem to be a way to modify this behavior through the extension settings.

**Suggested Solution:**
It would be great if we could have a configuration setting like "phpunit.useTeamcityFlag": true/false that determines whether to append the --teamcity flag during test execution.

**Comment by ljubadr** [comment]
Check `Output` panel in vscode for nicer output. Press `cmd+p` and type `view Output`. Then select phpunit in dropdown

You can also use following `settings.json` to open `Output` on every run

```json
"phpunit.showAfterExecution": "always",
```

I've setup `Output` and `Test Results` panels to be side by side so that I can see both at the same time

**Comment by recca0120** [comment]
To immediately receive test messages, you must add the parameters --teamcity and --color=never.
