### ISSUE TITLE
Open VSX version is outdated

### ISSUE THREAD

**Issue by hschletz** [recca0120/vscode-phpunit#176]
https://open-vsx.org/extension/recca0120/vscode-phpunit is still at 3.0.30.

**Comment by murklemike** [comment]
Here's instructions for installing/updating the extension manually in VSCodium for anybody looking for help on this issue and those who found themselves here wondering why **PHP: Unit Test Explorer UI** doesn't seem to work right.

1. Download the latest .vsix file from the extension's marketplace version history page. Here's a link to it, [version history](https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit).
2. Open a terminal, I used Powershell 7, at where you downloaded the file and enter the following command: 
    `codium --install-extension .\recca0120.vscode-phpunit-3.2.2.vsix`.

That's it. This will work for manually installing any VS Code extension in VSCodium but not all are 100% cross-compatible.

**Comment by recca0120** [comment]
update to 3.3.1
