### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by borekb** [recca0120/vscode-phpunit#18]
My problem probably is that this extension cannot find the PHPUnit binary (my tests live in a subfolder of a workspace, so the `vendor` folder is not at the top level) but the error given is rather mysterious:

```
(node:25214) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'file' of undefined
    at e.Controller.<anonymous> (/Users/borekb/.vscode/extensions/recca0120.vscode-phpunit-2.0.41/server/out/server.js:1:76244)
    at Generator.next (<anonymous>)
    at /Users/borekb/.vscode/extensions/recca0120.vscode-phpunit-2.0.41/server/out/server.js:1:74403
    at new Promise (<anonymous>)
    at s (/Users/borekb/.vscode/extensions/recca0120.vscode-phpunit-2.0.41/server/out/server.js:1:74180)
    at e.Controller.runFile (/Users/borekb/.vscode/extensions/recca0120.vscode-phpunit-2.0.41/server/out/server.js:1:76116)
    at e.Controller.<anonymous> (/Users/borekb/.vscode/extensions/recca0120.vscode-phpunit-2.0.41/server/out/server.js:1:75847)
    at Generator.next (<anonymous>)
    at /Users/borekb/.vscode/extensions/recca0120.vscode-phpunit-2.0.41/server/out/server.js:1:74403
    at new Promise (<anonymous>)
(node:25214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

I've also seen a similar error with `EACCES` which I cannot reproduce now.

It would be nice if a more useful message was printed.

**Comment by borekb** [comment]
Everything works beautifully if I open `subfolder` in a separate VSCode instance. However, having our workspace root open and trying to put something like this to `.vscode/settings.json` doesn't work:

```json
{
  "phpunit.phpunit": "${workspaceFolder}/subfolder/vendor/bin/phpunit",
  "phpunit.args": [
    "--configuration ./subfolder/tests/phpunit.xml"
  ],
}
```

**Comment by recca0120** [comment]
OK. I'll fix this problem at next version ...

**Comment by opus-2** [comment]
@borekb meanwhile, it might help to set your environment PATH variable to your phpunit bin folder, have you tried it?

**Comment by recca0120** [comment]
Try latest veraion

**Comment by borekb** [comment]
Thanks, it detects my tests now without any further configuration.

There's one problem though – it also scans gitignored folders, for example, I get tons of tests from the `subfolder/vendor` directory.
