### ISSUE TITLE
Ability to specify phpunit.xml location

### ISSUE THREAD

**Issue by shugyosha89** [recca0120/vscode-phpunit#180]
## Issue

Currently I'm unable to use the extension because my PHP code and phpunit.xml file are in a subdirectory of my workspace folder.

I see currently the expected location of phpunit.xml is hardcoded:

`const xml = parseXML(workspaceFolder.uri.path + '/phpunit.xml');`

## Proposed solution

Add a `phpunit.phpunitXmlPath` configuration setting allowing the user to specify the location of phpunit.xml relative to the workspace folder.

**Comment by ThatsJustCheesy** [comment]
For anyone who needs this working ASAP, a workaround is:

![image](https://github.com/user-attachments/assets/93d5b2b5-3ce3-442f-ad1b-fd570ab91fdb)

v3.2.2 from 11mo ago still works.

**Comment by shugyosha89** [comment]
Fixed in v3.3.4
