### ISSUE TITLE
Duplicating a test file breaks the test

### ISSUE THREAD

**Issue by Deji69** [recca0120/vscode-phpunit#19]
Steps to reproduce:
1. Create a test file e.g. `MyTest.php` with a class `MyTest`
2. Copy this test file in an attempt to quickly create a new test without writing from scratch, resulting in a `MyTest.1.php` file
3. Rename this `MyTest.1.php` file to the desired new test name e.g. `NewTest.php` and rename the class accordingly

Now the test explorer shows two tests called "MyTest", and both never go away and cannot be run. The following error occurs in the output for both "MyTest" tests (the original test filename is overridden by the temporary copy):
```
Cannot open file "...\MyTest.1.php"
```

The only way to fix this is to close the workspace and re-open it. The `NewTest` test however works fine.

**Comment by Deji69** [comment]
Actually, I probably over-complicated it a bit there, the issue also exists if you simply want to rename an existing test/file - the old test doesn't go away.

**Comment by recca0120** [comment]
Fix this problem later

**Comment by recca0120** [comment]
try version 3.0
