### ISSUE TITLE
Do not auto-detect tests from `vendor`, recursively

### ISSUE THREAD

**Issue by borekb** [recca0120/vscode-phpunit#20]
After the recent change in #18 which added recursive scanning for tests (I think), I get a lot of tests that are not "mine" but from `vendor` directories:

<img width="1242" alt="Screenshot 2019-05-20 at 09 02 20" src="https://user-images.githubusercontent.com/101152/58002242-1da21280-7ade-11e9-9bd8-9dcd820b302c.png">

I think the solution could be to automatically skip gitignored directories.

(This behavior is without any custom config. It's possible that I will be able to work around this by setting PHPUnit configuration via `phpunit.args` but I still think that by default, gitignored directories should not be scanned.)

**Comment by recca0120** [comment]
skip all vendor folder now
