### ISSUE TITLE
Feature Request: Ability to Set Environment Variables During Test Execution

### ISSUE THREAD

**Issue by KentarouTakeda** [recca0120/vscode-phpunit#204]
Hello Tsai,

Thank you for creating such a useful tool. I've been using it for a few days, and it has definitely improved my developer experience.

I would like to request the addition of a feature that allows setting arbitrary environment variables during test execution.

I'm confident that this feature would make the tool even more convenient in several use cases.

## Using Xdebug

Enabling Xdebug significantly slows down execution, so I prefer to disable it by default:

```ini
[xdebug]
xdebug.mode = off
xdebug.start_with_request = yes
```

and only enable it via environment variables when needed:

```sh
$ XDEBUG_MODE=debug phpunit
```

## Utilizing Framework Features

Many frameworks have features that allow controlling behavior through environment variables. For example, in Laravel, we can switch the configuration files loaded by setting `APP_ENV`.

For instance, running `phpunit` from the command line is intended for CI environments, whereas executing it from a GUI tool allows us to run each test individually. Such switching can make testing more efficient:

```sh
$ APP_ENV=phpunit-for-vs-code phpunit
```

## Feature Request

It seems that these functionalities are not currently available in *PHPUnit for VSCode*.

* When I added the above settings to `phpunit.php` or `phpunit.phpunit`, the tests failed to start. It appears that the entire string is recognized as the execution command.
* Adding `-d xdebug.mode=debug` to `phpunit.args` did not work either. It seems that the environment variables need to be set before the PHP command is executed.

I would appreciate your consideration.

Sincerely,

**Comment by ljubadr** [comment]
I use following settings with docker and I'm able to set the environment variables in `"phpunit.command"`

```json
"phpunit.command": "docker exec -t -e XDEBUG_TRIGGER=vscode -e XDEBUG_MODE=debug,develop [container_name]",
"phpunit.phpunit": "vendor/bin/phpunit",
"phpunit.php": "php",
"phpunit.args": [
    "-c",
    "phpunit.xml",
],
"phpunit.paths": {
    "${workspaceFolder}": "/var/www/html"
},
```

Maybe you can try to use `"phpunit.command"` for variables

```json
"phpunit.command": "XDEBUG_MODE=debug"
"phpunit.phpunit": "vendor/bin/phpunit",
"phpunit.php": "php",
```

**Comment by KentarouTakeda** [comment]
`XDEBUG_MODE=debug` is NOT a command, therefore we can not `spawn` it.

https://github.com/recca0120/vscode-phpunit/blob/4cc78941de6bb56a98805e2813e008c992ffa23d/src/PHPUnit/TestRunner.ts#L65

<img width="529" alt="spawn-environment-variable" src="https://github.com/user-attachments/assets/605d4e61-197a-4887-a4c1-b0ebe569ad9c">

**Comment by recca0120** [comment]
3.4.26

```
{
    "phpunit.environment": {
        "XDEBUG_MODE": "debug"
    }
}
```

**Comment by KentarouTakeda** [comment]
I've verified that it works as intended.

This will allow teammates who are not so familiar with CLI to easily use XDebug. I'll let everyone know about your tool soon.

Thanks for the great work.

Cheers.

![vscode-phpunit-with-xdebug](https://github.com/user-attachments/assets/41087195-6652-4a51-bbac-a3dfab2b6ddf)
