### ISSUE TITLE
${workspaceFolder} appears to not be correctly mapping.

### ISSUE THREAD

**Issue by mrenyard** [recca0120/vscode-phpunit#206]
When using ${workspaceFolder} in settings.json it looks to be equating to "/ ./"  even when set within settings.json, meaning that the below setting prepend "/ ./" to the paths for phpunit and our arguments, produce the following command:
```
php /./tools/phpunit.phar --configuration=/./tools/phpunit.xml --colors=never --teamcity
```
While "./" makes sense, as presumably we are running from within the ${workspaceFolder} the proceeding "/ " would look to be superfluous.  
 
```json
{
  "phpunit.php": "php",
  "phpunit.phpunit" : "${workspaceFolder}/tools/phpunit.phar",
  "phpunit.args": [

    "-c",
    "${workspaceFolder}/tools/phpunit.xml"
  ],
  "editor.tabSize": 2,
  "phpunit.paths": {
  
    "${workspaceFolder}": "/home/mrenyard/Projects/RAMP"
  },
}
```

I really appreciate all that you are doing with the extension as it is by the far the most important and useful tool in my development lifecycle.

**Comment by ili101** [comment]
Looks like we came to the same conclusion (:
https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2486574157

**Comment by mrenyard** [comment]
@recca0120 FYI This is still an issues with the latest update v3.4.9
Many thanks for the work. M.

**Comment by recca0120** [comment]
vscode is under WSL too ?

**Comment by recca0120** [comment]
PHP under WSL, but VSCode under windows 10 ?

**Comment by JonathanGawrych** [comment]
We are experiencing the same issue. We are on macOS Sonoma (M3 chips). Currently we are working around it by hardcoding the full path. Since we are using docker compose, we have to hardcode the path to docker-compose.yml too:

```json
"phpunit.command": "docker compose -f /Volumes/code/work/GoREACT/docker-compose.yml exec v2 /bin/sh -c",
"phpunit.paths": {
    "/Volumes/code/work/GoREACT/goreact-api-v2": "/www/goreactv2/"
},
```

**Comment by recca0120** [comment]
3.4.10 fix this bug and you can do like this setting

```json
{
     "php": '${bin}/php'
     "phpunit.paths": {
         "${BIN}": '/usr/local/bin'
     }
}
```

**Comment by mrenyard** [comment]
@recca0120 Yes thanks 3.4.10 now fixes this particular issues, Thank you.

**Comment by JonathanGawrych** [comment]
Unfortunately it seems like this still isn't working for me, even outside the docker container. `${workspaceFolder}` still resolves to just `/`. Maybe it's because I'm on a mac? I'm using version v3.4.16
