### ISSUE TITLE
v3.4.10: Cannot longer run tests with PHP instance in Docker Container + Windows

### ISSUE THREAD

**Issue by pjaydev** [recca0120/vscode-phpunit#210]
I cannot run my PHP tests anymore since the update to v3.4.10. 

When starting a test, the circle next to the test name keeps spinning, but nothing happens and there is no log output. There is also no way to cancel the test once started (cancel requests are ignored).

I have my PHP instance including PHPUnit running inside a Docker container, and I initiate the test using a Powershell script (a workaround since the arguments were not properly passed, if I directly used `docker compose exec ...` as command) .

This is my configuration:
```json
{
    "phpunit.command": "powershell ${workspaceFolder}\\docker\\phpunit_docker.ps1",
    "phpunit.php": "",
    "phpunit.paths": {"${workspaceFolder}" : "/var/www/html"}
}
```

This is the powershell script `.\docker\phpunit_docker.ps1`:
```powershell
param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Args
)

$command = "docker"
$commandArgs = @("compose", "exec", "web", "vendor/bin/phpunit") + $Args

& $command @commandArgs
```

Up to v.3.4.9, this approach worked absolutely fine.

**Comment by recca0120** [comment]
try 3.4.12

**Comment by pjaydev** [comment]
It's working again. Thank you for your great work!
