### ISSUE TITLE
how to remove the default options ex.`--colors`

### ISSUE THREAD

**Issue by ctf0** [recca0120/vscode-phpunit#217]
thank you so much for your work.

atm am trying to use the extension with **codeception** which have the colors option but without any values, which conflicts with the default `--colors=never`

is there away to disable the default options the extension adds ?

or maybe as a work around, we can have the extra options like this as defaults for the `phpunit.args` this way the user can change it to their needs.

**Comment by recca0120** [comment]
To immediately receive test messages, you must add the parameters --teamcity and --color=never.
