### ISSUE TITLE
Doesn't recognise failures from data providers

### ISSUE THREAD

**Issue by Deji69** [recca0120/vscode-phpunit#22]
When `@dataProvider` is used to run the same test over multiple data sets, the test will appear to have passed in the Code Lens and the Test Explorer as long as _any one_ of the data sets passes the test, even though the output window shows failures and errors on the other data sets.

**Comment by recca0120** [comment]
I need sample code to confirm this issue.

**Comment by david-nagel** [comment]
This code will fail but show as passed:
```
<?php
use PHPUnit\Framework\TestCase;
final class Test extends TestCase {
    /**
     * @dataProvider provider
     */
    public function testProvider($x): void {
        $this->assertLessThanOrEqual(1, $x);
    }
    public function provider() {
        return [[0], [1], [2]];
    }
}
```

**Comment by recca0120** [comment]
fixed
