### ISSUE TITLE
In 3.4.20 having `/bin/sh -c` causes tests to hang

### ISSUE THREAD

**Issue by ljubadr** [recca0120/vscode-phpunit#221]
I'm creating this issue from [this comment](https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2518865435)

In version `3.4.20` having `/bin/sh -c` in the `phpunit.command` causes tests to hang and they never finish. If I remove `/bin/sh -c` then tests run normally. I saw that `/bin/sh -c/` was removed in [readme docker section](https://github.com/recca0120/vscode-phpunit?tab=readme-ov-file#docker).

This doesn't work anymore

```json
"phpunit.command": "docker exec -t [container_name] /bin/sh -c",
```

This works

```json
"phpunit.command": "docker exec -t [container_name]",
```

@recca0120 you [confirmed in this comment](https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2519073333) that it's a breaking change

**Comment by recca0120** [comment]
fixed
