### ISSUE TITLE
Vendor tests in the testing sidebar

### ISSUE THREAD

**Issue by kathibeepboop** [recca0120/vscode-phpunit#226]
Why are now all the vendor tests in my sidebar?  
Wasnt there before the latest update
Also its loads a very long time

At first i see this
![image](https://github.com/user-attachments/assets/b0540cde-1db4-46c9-a3ee-794dbc174df2)

Waiting a few minutes it shows this
![image](https://github.com/user-attachments/assets/0e649a71-3152-4cfe-98d8-c9b67fbfd2ae)

**Comment by kathibeepboop** [comment]
nvm.
fixed by https://github.com/recca0120/vscode-phpunit/issues/218

**Comment by tm1000** [comment]
@kathibeepboop how exactly did that fix it?

**Comment by jansgescheit** [comment]
Same Issue with the latest version
