### ISSUE TITLE
Did not detect the first test function in the test case correctly

### ISSUE THREAD

**Issue by shingo0620** [recca0120/vscode-phpunit#24]
If the first function name is starting with "test", the detection is working good.

But if the first function function is using comment /** @test */, the detection would skip this function.
![螢幕快照 2019-05-25 16 32 13](https://user-images.githubusercontent.com/359648/58366833-acfa5c00-7f0a-11e9-9065-013ded7d9359.jpg)

**Comment by recca0120** [comment]
would you send this test file to me??

**Comment by shingo0620** [comment]
Sure, have a look please.
[ProjectTaskTest 拷貝.txt](https://github.com/recca0120/vscode-phpunit/files/3219246/ProjectTaskTest.txt)

**Comment by recca0120** [comment]
fixed
