### ISSUE TITLE
Test reloading problem

### ISSUE THREAD

**Issue by Deji69** [recca0120/vscode-phpunit#26]
Upon first opening a folder/workspace, all the tests seem to be discovered and shown in the Test Explorer, even if they are not present within `phpunit.xml`.

![image](https://user-images.githubusercontent.com/6594342/59161303-0486f300-8ad9-11e9-836f-dbb6a970b42f.png)

However, upon editing a file, or clicking the "reload tests" button, all the tests configured in the test suites in `phpunit.xml` vanish, leaving only the ones that shouldn't have been there in the first place.

![image](https://user-images.githubusercontent.com/6594342/59161334-5def2200-8ad9-11e9-9a6f-9794d8b411f9.png)

**Comment by recca0120** [comment]
https://github.com/recca0120/vscode-phpunit/blob/master/package.json#L126-L137

I add this option to find where test files are. try this option.

**Comment by Deji69** [comment]
Ah, that indeed works. Just seems inconsistent that all the tests show up to begin with and then disappear...

**Comment by recca0120** [comment]
@Deji69 
I can't understand what you mean.
can you record a video.

thx

**Comment by recca0120** [comment]
maybe fixed at new version
