### ISSUE TITLE
Autorun not triggering.

### ISSUE THREAD

**Issue by MichMich** [recca0120/vscode-phpunit#27]
I'm very new to writing tests and using phpunit, but so far your extension helped me a lot. The inly thing I'm not getting to work is the autorun feature. 

I can enable autorun, and the tiny 'play triangle' gets added to the test icons. But when I change and save any file. None of the tests are automatically triggered.

Am I forgetting anything? Thanks!

**Comment by recca0120** [comment]
Not implemented yet

**Comment by MichMich** [comment]
Ah! That explains a lot. :)

**Comment by recca0120** [comment]
autorun is working.
