### ISSUE TITLE
Thank you very much and willing to help

### ISSUE THREAD

**Issue by swashata** [recca0120/vscode-phpunit#28]
Hello,

First off, thank you very much for this extension. I have used it and it works very good. Hats off :)

Now I see some of the features aren't being implemented and I would like to lend a hand. If you have some sort of roadmap or contribution guide, do let me know 👍

**Comment by recca0120** [comment]
maybe support ssh, docker

**Comment by swashata** [comment]
Do you know of any other extension of similar type with support for ssh and docker?

**Comment by recca0120** [comment]
https://marketplace.visualstudio.com/items?itemName=emallin.phpunit
https://marketplace.visualstudio.com/items?itemName=calebporzio.better-phpunit
