### ISSUE TITLE
Failed tests remains in problems and editor after fixing

### ISSUE THREAD

**Issue by swashata** [recca0120/vscode-phpunit#29]
Hello,

I have encountered a bug I believe. Say I have a test failing. If I run it, it shows up as Decoration, in the PROBLEMS (panel) and also as wiggly underline.

Now if I start changing the file, the Decoration goes away. Once I have fixed the test and run it again, the cross mark on the gutter turns to green check. But the PROBLEMS panel and the wiggly underline stays.

Do let me know if I am able to explain the issue, otherwise I will post a screenshot or video.

**Comment by recca0120** [comment]
screenshot or video please.

**Comment by swashata** [comment]
Hello,

I was trying to recreate it, but strangely I wasn't able to. I think, it happens, if for some reason, the previous PHPUnit process doesn't end properly. I will keep on digging as to why and when this happens.

**Comment by swashata** [comment]
Hello,

I have found the way to reproduce. It happens if during testing the whole class, there is an error in the output with `PromiseRejection`. Then the test results and editor decorations stays even after passing tests.

Please see this video.

https://youtu.be/GC09p48jQhc

I shall also add that after restarting VSCode, I wasn't able to reproduce it.

**Comment by recca0120** [comment]
could you share the project in this video to me ?

**Comment by swashata** [comment]
sure, are you gitlab.com? I would add you to the project then (it is a private project).

**Comment by swashata** [comment]
Also I don't understand much but I think it could be related to #21

**Comment by recca0120** [comment]
https://gitlab.com/recca0120?nav_source=navbar

this is my gitlab account

**Comment by swashata** [comment]
Sorry for the long delay. I got caught up with some project. I have added you to our project `wp-eform`. Please let me know when you have downloaded.

**Comment by recca0120** [comment]
try version 3.0
