### ISSUE TITLE
Include parameters

### ISSUE THREAD

**Issue by ErickTucto** [recca0120/vscode-phpunit#32]
Include parameters, example `coverage-clover`
this is useful for the coverage report
![Captura de pantalla de 2019-07-06 22-25-21](https://user-images.githubusercontent.com/22831024/60763594-3e4a0b80-a03d-11e9-87eb-be17c69a2750.png)

**Comment by recca0120** [comment]
settings.json
```json
{
    "phpunit.args": ["--coverage-clover", "cov.xml"]
}
```

**Comment by ErickTucto** [comment]
Thanks,it works :+1:
