### ISSUE TITLE
Use @testdox annotation as a more human readable name for tests in the explorer sidebar

### ISSUE THREAD

**Issue by AlmightyTritan** [recca0120/vscode-phpunit#35]
One of the nicer parts about writing unit tests for other frameworks, such as Jest or Spock is the ability to have human readable test names. PHPUnit kind of does this by having the `@testdox` annotation in the DocBlock.

It would be super handy if the annotation could be used as the test name in the sidebar if present.

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by recca0120** [comment]
supported
