### ISSUE TITLE
Projects that don't contain any *Tests.php files are indexed in the sidebar of the Test Explorer

### ISSUE THREAD

**Issue by AlmightyTritan** [recca0120/vscode-phpunit#37]
In a multi-folder workspace, all projects are indexed in the sidebar even if they don't contain any `*Tests.php` files.

Currently none of these projects have any PHPUnit tests
![image](https://user-images.githubusercontent.com/9136544/63352684-f30f6200-c337-11e9-8fa1-ab4d61048cad.png)

**Comment by recca0120** [comment]
I need your project files to fix this bug.

**Comment by AlmightyTritan** [comment]
Can you clarify this a bit for me? Do you need to know my project file structure, because I would be happy to provide that to you, however if you mean you need access to the projects I can't do that as they are proprietary.

One other piece of information that I can provide at this time is that it seems to only be doing this when I have multiple projects open in a workspace. The detection happens regardless of if there are any matches for the test file pattern.
