### ISSUE TITLE
Tests won't run 

### ISSUE THREAD

**Issue by you2-0** [recca0120/vscode-phpunit#38]
Tests are running just fine using the PHPUnit command line but I got those odd warnings with the VSC extension :

![image](https://user-images.githubusercontent.com/39281417/63581267-f5bbc280-c596-11e9-81f5-9b4a19c5a0a7.png)

**Comment by recca0120** [comment]
1. uninstall vscode
2. remove ~/.vscode
3. install vscode

you can try those three steps, it maybe work.

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by dkgs** [comment]
Hi, I'm having the same symptoms, but maybe the source of the problem is different.
In my case, the path to the workspace folder contains a space. Moving the workspace to a spaceless path works for me.

**Comment by siburny** [comment]
See the comment in the other issue: https://github.com/recca0120/vscode-phpunit/issues/68#issuecomment-739108388

**Comment by MilesHart** [comment]
I had this issue, if your path to the project has a space in it, remove it. This should be raised as a bug.

**Comment by recca0120** [comment]
try version 3.0
