### ISSUE TITLE
Using relative path

### ISSUE THREAD

**Issue by Fanny42** [recca0120/vscode-phpunit#39]
Hello !
I can't find any way to set a relative path for phpunit.
I am using Symfony, and I don't want to update setting.json every single time I start a new project, nore add a local `.vscode/settings.json` file.
Isn't it possible to use a variable like `${workspaceFolder}` to find `bin/phpunit` in everyworkspace ?

**Comment by recca0120** [comment]
I'll try fix this later

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by charlesg99** [comment]
+1 I'd also like relative path as it is a bit cumbersome with Symfony.

**Comment by aphix-mark** [comment]
Does the recent update to `"phpunit.relativeFilePath": true,` give you what you need here?

**Comment by mikebronner** [comment]
@aphix-mark It doesn't appear to work. When specifying a relative path, it still tries to execute phpunit using an absolute path:
```
spawn /./tools/phpunit ENOENT
```

With the following config settings:
```json
    "phpunit.phpunit": "./tools/phpunit",
    "phpunit.relativeFilePath": true,
```

**Comment by janfschmidt** [comment]
I observe exactly the same behavior as @mikebronner.
@aphix-mark `"phpunit.relativeFilePath": true` seems to be ignored

**Comment by recca0120** [comment]
try version 3.0
