### ISSUE TITLE
Cannot read property 'testsuite' of undefined   Code

### ISSUE THREAD

**Issue by killworm737** [recca0120/vscode-phpunit#4]
PHP 5.6.3  
PHPUnit 5.7.21-17-g4eba337 by Sebastian Bergmann and contributors.

![error](https://user-images.githubusercontent.com/8952873/38475491-1e49e32c-3bdb-11e8-9327-803ac632498f.png)

**Comment by killworm737** [comment]
![phpunittest](https://user-images.githubusercontent.com/8952873/38476182-efb07162-3bde-11e8-99b2-dc0be0d6be60.gif)

**Comment by recca0120** [comment]
有辦法整理出案例內容嗎？
我沒遇到這個問題

**Comment by killworm737** [comment]
找到錯誤原因了，function命名不能使用中文

![phpunittest2](https://user-images.githubusercontent.com/8952873/38478665-e5a5ef0e-3bec-11e8-947b-448a933469fc.gif)

**Comment by recca0120** [comment]
我剛剛測在自己的電腦測中文名是沒問題的
真怪異 ...

**Comment by zhi8617** [comment]
/** @test */
     public function 中文()
    {        
        $this->assertTrue(true);        
    }

我也是OK
