### ISSUE TITLE
Running single test sometimes causes full test suite to run

### ISSUE THREAD

**Issue by shawnhind** [recca0120/vscode-phpunit#41]
I haven't been able to track down a specific cause of this.

Occasionally when I'm in a test file and click the "run" button that the extension includes above the test it will run the full test suite rather than the individual test.

Sometimes clicking it doesn't appear to do anything and I have to click it multiple times and I think this is when it's trying to run the full test suite.

I know I don't have many details in this issue but just wondering if other people are experiencing it so we can maybe find some common info?

**Comment by shawnhind** [comment]
I've found what's causing this but not sure what the best approach to fixing it would be.  This is occurs when you save a test file and then click run before the extension finishes "processing".  

When you update a test file and have the activity bar open to the test explorer you'll see that there's a spinner that appears (in my repo it appears for around 10 seconds).  If you click run on a single test (or single file) during this time it causes all tests to run rather than the individual test (or tests) that you triggered.

Now that I know what's causing it I can at least work around it.  Hopefully this helps someone else.

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by shawnhind** [comment]
@recca0120 awesome!  I'm glad to hear that.  I use this every day and other than this problem it works great

**Comment by recca0120** [comment]
try version 3.0
