### ISSUE TITLE
Test Explorer doesn't show all tests in suite.

### ISSUE THREAD

**Issue by itaibh** [recca0120/vscode-phpunit#43]
I have a test suite that uses inheritance, so I have an abstract base class (`TestSetup`) that extends `TestCase`, then I have another abstract class that implements the actual test methods (let's call it `TestsImpl`) and extends `TestSetup`, then I have concrete classes that each provides a different configuration to `TestImpl`.

So you can think of the hierarchy as `TestImplConfA` > `*TestImpl` > `*TestSetup` > `TestCase`

While PHPUnit runs all these tests, the test explorer doesn't show them.

The test methods are marked with `@test` comment attribute.

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by recca0120** [comment]
try version 3.0
