### ISSUE TITLE
phpunit.php and phpunit.phpunit doesn't fallback to default values

### ISSUE THREAD

**Issue by jimmy4o4** [recca0120/vscode-phpunit#44]
Hello,

I'm trying to use vscode 1.40.1 (windows 10 x64) with PHPUnit Test Explorer extension (2.0.72), but can't get it to work without setting phpunit.php and phpunit.phpunit settings as package.json states:

```json
"phpunit.php": {
	"type": "string",
	"description": "Absolute path to php. Fallback to global php if it exists on the command line."
},
"phpunit.phpunit": {
	"type": "string",
	"description": "Path to phpunit. Can be the phpunit file or phpunit.phar.\n\nAutomatically finds it in common places:\n  - Composer vendor directory\n  - phpunit.phar in your project\n  - phpunit (or phpunit.bat for windows) globally on the command line"
},
```

I have php executable in environment path and phpunit installed in vendor/phpunit/phpunit, but only result I get is:
`spawn -c ENOENT`

When I set BOTH of these settings to absolute paths, everything is working OK, but that is not what I wanted to achieve.

Is there any way to get it sorted out?

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version
