### ISSUE TITLE
Access file code from right click menu

### ISSUE THREAD

**Issue by rstriquer** [recca0120/vscode-phpunit#49]
I feel kind of silly thowing a question like that, I guess it would have a reason not to, for it seams to be to be a pretty basic function but ... would'nt it be  nice to have some kind of "Open File" or "Reveal on sidebar" option when you right click a test on the Test Explorer?

By what I understand the Test Explorer is part of the Test Explorer UI and therefor it would have some options where the file been used is not sourcecode, but when talking about PHP I guess we can count about 99,99% os the files would be simple sourcecode.

**Comment by recca0120** [comment]
try version 3.0
