### ISSUE TITLE
test explorer don't work

### ISSUE THREAD

**Issue by RyuJin137** [recca0120/vscode-phpunit#51]
Hello,
my test explorer doesn't works :( , i've tested uninstal, delete .vscode folder and reinstall but no success . Could you help me please 
![image](https://user-images.githubusercontent.com/58660630/74990236-a6b5f380-543a-11ea-890b-a1fc09ebdaaf.png)

**Comment by Axel-KIRK** [comment]
Same here, it work once ... I change something maybe disable package or something and couldn't work anymore..

**Comment by RyuJin137** [comment]
Super ça fonctionne, merci mec 👍 😄
