### ISSUE TITLE
unable to call parent::setUp() and causes whole test suite break

### ISSUE THREAD

**Issue by nomadbard916** [recca0120/vscode-phpunit#52]
Laravel version: 5.8
PHP version: 7.2.19
phpunit version: 7.5.17
OS: Windows 10 professional 1809
Node.js version: 12

I got a test file that calls setUp() at the very beginning with calling setUp() in TestCase.
When I run all the tests with this extension, the first error was "ReflectionException: Class env does not exist", making all next tests unfunctional with the same exception.

**Comment by recca0120** [comment]
try version 3.0
