### ISSUE TITLE
Feature request: Go to test from context menu in test explorer

### ISSUE THREAD

**Issue by nerdo** [recca0120/vscode-phpunit#54]
I'm loving this extension. It has worked really well but one thing that I feel is missing is a `Go to test` from the context menu when you right click on a test in the explorer. There are obvious workarounds, but having a quick way to do this seems like a quick win.

**Comment by nerdo** [comment]
So I just glanced at the screenshot of the extension and realized that there *is* a button for it, but it doesn't show  if the panel is too small, which is why I missed it in the first place. In my project the side panel has to be quite wide (way too wide) in order for it to show, so if that is fixed so that it shows regardless of the width of the panel and/or it was added to the context menu, it would solve this issue.

**Comment by recca0120** [comment]
try version 3.0
