### ISSUE TITLE
PHPUnit Running notification doesn't dismiss

### ISSUE THREAD

**Issue by squareborg** [recca0120/vscode-phpunit#56]
Hello. Thanks for your excellent package.

I have autorun on for tests. I get a notification when the tests start running.  However, the notification doesn't auto dismiss, sometimes the notifications will stack up to 3 notifications all un dismissable ( without lots of clicking ) It appears after the tests have run the notifications stack up. 

With auto run and autosave enabled, I quickly get a barrage of notifications.

<img width="560" alt="Screenshot 2020-03-19 at 07 49 20" src="https://user-images.githubusercontent.com/8677881/77044235-f5fa3000-69b6-11ea-9f77-ca431405d591.png">

Is there an issue here? Also Is there a way to stop notifications? I don't really need them.

**Comment by Phylhum** [comment]
Same for me ... "PHP Unit Running ..." won't stop.
Sometimes many `notifications` stack up in notification list ... no way to `cancel` or `stop` running process ? 
Or is it only a cosmetic issue (which will then not be really a big thing)

**Comment by recca0120** [comment]
try version 3.0
