### ISSUE TITLE
Is it possible to specify the `cwd`?

### ISSUE THREAD

**Issue by hunhejj** [recca0120/vscode-phpunit#62]
I need to run tests from within a specific directory otherwise they will fail. I know, these tests are badly designed, but is there any way I could achieve this?

**Comment by rilex037** [comment]
same here, my tests are not even showing, because they are inside source dir

**Comment by bagage** [comment]
Same here - you can make tests appear with:

```
  "phpunit.args": ["--configuration=my-subfolder/phpunit.xml.dist"],
  "phpunit.files": "./my-subfolder/test/**/*Test.php"
``` 

But it won't work if your workdir should be `my-subfolder` because all dependencies are missing then.

**Comment by rilex037** [comment]
what i did was :

```
    "phpunit.files": "source/{test,tests}/**/*Test.php",
    "phpunit.phpunit": "/home/rilex/docker/enode5/sanity/test.sh"
```

and inside test.sh just `docker-compose exec -T php-fpm vendor/bin/phpunit`. which probably could just be replaced with path to phpunit for non docker environment, and everything works great
