### ISSUE TITLE
Prevent auto-focus of Output panel

### ISSUE THREAD

**Issue by eballeste** [recca0120/vscode-phpunit#65]
I just installed this extension for the first time and I'm trying to figure out how to prevent the `output` panel from stealing the focus from my `terminal` panel each time I run a test. I tried closing/hiding the output panel but this extension still opens it again.

**Comment by recca0120** [comment]
try version 3.0

**Comment by olexoliinyk0** [comment]
It still does that on v3.3.3 for me. Only for failed / skipped tests. It steals cursor focus from anywhere I type, same if I switch to an other window - it pops VSCode and that Output tab over anything.
