### ISSUE TITLE
Unable to load custom config file

### ISSUE THREAD

**Issue by yanikore** [recca0120/vscode-phpunit#7]
I have the following configuration:
```
"phpunit.execPath": "D:\\webdev\\www\\project\\app\\vendor\\bin\\phpunit.bat",
    "phpunit.args": [
        "-c D:\\webdev\\www\\project\\app\\vendor\\bin\\phpunit.xml"
    ]
```

It does however not seem to load the bootloader which is configured as such:

```
bootstrap="D:\\webdev\\www\\compufact\\app\\core\\bootstrap.php"
````

I also tried with quotes and a few other things. Am I doing something wrong?

Thanks

**Comment by recca0120** [comment]
['-c', 'D:\\webdev\\www\\project\\app\\vendor\\bin\\phpunit.xml']
