### ISSUE TITLE
"&amp;" shows as "&" in the tab "Problems" and the tab "Output/Test Explorer"

### ISSUE THREAD

**Issue by hanak** [recca0120/vscode-phpunit#74]
Consider following test:
```
public function testTest() {
    $result = 'Mac&amp;Cheese';
    self::assertEquals('Mac&Cheese', $result);
}
```
The test fails as expected. Yet, the tab "PROBLEMS" shows:
![image](https://user-images.githubusercontent.com/178428/94064630-416c1b80-fdea-11ea-9498-6110fdcf9d9f.png)

And, the "OUTPUT" / "Test Explorer" shows:
![image](https://user-images.githubusercontent.com/178428/94064697-5b0d6300-fdea-11ea-9005-b0ad801b51c5.png)

Only "OUTPUT" / "PHPUnit Language Server" shows the correct report:
![image](https://user-images.githubusercontent.com/178428/94064795-7a0bf500-fdea-11ea-8f5a-40c26127af0a.png)

PHPUnit 2.0.76
VSCode 1.49.1

**Comment by recca0120** [comment]
try version 3.0
