### ISSUE TITLE
Can't find simlink test files

### ISSUE THREAD

**Issue by tyler36** [recca0120/vscode-phpunit#77]
I have a setup with packages install in either `web\modules\contrib` & `web\modules\custom`. 
This extension will find test in either package with:
```
    "phpunit.files": "web/modules/**/*Test.php"
```

However, if I use compose to symlink to a package, tests do not appear. EG.
✅ `web\modules\contrib\example\test\ExampleTest.php` is listed
1. Move `example` to `c:\test\example` and create a symblink `web\modules\contrib\example` => `c:\test\example`
2. Explorer / VSCode show files and navigation
❌ TestUI no longer displays test.
 - 'Reload test' does not help.

3. Remove symlink
4. Copy `example` back into `contrib`
✅- `Reload tests` shows tests again

So it feels like the extension does not "follow" symlinks but not really sure. 🙁

PHPUnit Test Explorer: 2.0.76
Test Explorer UI: 2.19.3
VSCode: 1.51.1
OS: Win10

**Comment by recca0120** [comment]
try version 3.0
