### ISSUE TITLE
* feature request * paratest

### ISSUE THREAD

**Issue by paul-a-byford** [recca0120/vscode-phpunit#80]
hi,
is it possible for the extension to support test execution through the php until paralell test runner? 

https://github.com/paratestphp/paratest

**Comment by fabianogaldino** [comment]
Try change "phpunit.phpunit": "/path/to/project/vendor/bin/paratest"

**Comment by sebastienbarre** [comment]
Can this be a relative path? I tried `vendor/bin/paratest`, and that didn't work.
I'm getting an error:
```
spawn /vendor/bin/paratest ENOENT
```
