### ISSUE TITLE
No Output on the last Version of VSCODE

### ISSUE THREAD

**Issue by Baptou88** [recca0120/vscode-phpunit#82]
since the last update of VScode i can't execute tests. Each Tests fail and i'have no output on the console

`Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042`

**Comment by recca0120** [comment]
try version 3.0
