### ISSUE TITLE
Is it possible to add this extension to VSCodium marketplace

### ISSUE THREAD

**Issue by FlorianGG** [recca0120/vscode-phpunit#85]
As explained in the title, since few weeks I migrated to VSCodium and I have to use VSIX file to use your extension. So can you add it to the vscodium marketplace please?

**Comment by recca0120** [comment]
yes, l will add it to vscodeium marketplace

**Comment by FlorianGG** [comment]
It seems that the extension is not still available on VSCodum. Thanks

**Comment by recca0120** [comment]
https://open-vsx.org/extension/recca0120/vscode-phpunit here.
but it show some warning, I'll try to fix it
