### ISSUE TITLE
Missing status bar progress spinner

### ISSUE THREAD

**Issue by swashata** [recca0120/vscode-phpunit#9]
Hi,

There used to be a small spinner in the status bar when I click on "Run Test" through code lens. But with the latest update it is gone.

Could you please tell me, if this was intended or maybe my vscode is messed up?

**Comment by recca0120** [comment]
hi @swashata 

I remove spinner now,
I'll add spinner at next version

**Comment by swashata** [comment]
Great to know. Thanks.
