### ISSUE TITLE
Feature request: omit test name prefix in test list

### ISSUE THREAD

**Issue by enricodias** [recca0120/vscode-phpunit#94]
Showing the test name prefix (such as `test_`) seems like a waste of space, especially when the tests have lengthy names.

It would be nice to have an option in the settings to omit that prefix.

**Comment by cezaro** [comment]
It would be nice to have option to customize tests' tree. I would like to replace `Tests\Feature\` with `Feature\` or `F\` 
<img width="129" alt="image" src="https://user-images.githubusercontent.com/30954708/145859257-b9bd4a84-c3c5-430e-853a-60f9913d8ac2.png">

**Comment by bfranklyn** [comment]
Could you provide a setting similar to the previous "phpunit.files" for configuring how to find test files?
