### ISSUE TITLE
Paths for single tests

### ISSUE THREAD

**Issue by nunoperalta** [recca0120/vscode-phpunit#96]
Hello,

I develop on Windows, but run on Linux (docker).

I managed to get this extension to work, with:

	"phpunit.logpanel": true,
	"phpunit.php": "",
	"phpunit.phpunit": "C:\\node\\npm.cmd",
	"phpunit.args": ["run", "build-runtests", "--"],
	"phpunit.relativeFilePath": true,
	"phpunit.remoteCwd": "/opt/app/",
	"phpunit.files": "myapp/tests/*Test.php",
		
But that's only if I run ALL tests.

If I want to run just one test, the command will append the PHP path as:

    ...  "/.*::testMyUnitTest.*$/" "myapp\\tests\\ThisTest.php"

And then it fails:

> Cannot open file "myapp\\tests\\ThisTest.php".
> 1

Is it possible to customize the way the paths are sent, so that we put our own prefix before "ThisTest.php"?
So what's sent is something like:

> /path/to/myapp/tests/ThisTest.php

Thank you.

**Comment by nunoperalta** [comment]
I created a "run_phpunit.php" inside the container so that it replaces "myapp\\tests\\" with "/path/to/myapp/tests/".

The problem is that when the tests fail, instead of showing the output of the failure, the whole thing just crashes because it tries to find "/path/to/myapp/tests/" on my PC:


> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ENOENT: no such file or directory, open **'f:\path\to\myapp\tests\ThisTest.php'**
> Emitted 'error' event on ReadStream instance at:
>     at internal/fs/streams.js:147:14
>     at FSReqCallback.oncomplete (fs.js:171:23) {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: **'f:\\path\\to\\myapp\\tests\\ThisTest.php'**
> }
> [Info  - 8:44:11 PM] Connection to server got closed. Server will restart.
>

**Comment by pattiereaves** [comment]
I think I am having a similar issue and looking for help. My environment is Mac OS local / Vagrant remote.

this is my configuration:
```
    "phpunit.relativeFilePath": true,
    "phpunit.phpunit": "/usr/bin/phpunit",
    "phpunit.php": "/usr/local/bin/vagrant exec php",
    "phpunit.files": "plugins/my-plugin/**/test-*.php",
    "phpunit.shell": "/bin/zsh", 
    "phpunit.args": ["-c", "/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/phpunit.xml"],
    "phpunit.remoteCwd": "/srv/www/wordpress/public_html/wp-content",
```

Where the workspace is the wp-content directory.

This plugin works as expected when running all of the tests but if I want to run a single file's test, it fails. It appears its because it is passing the relative path to the command and not using remoteCwd

from the verbose output:
```
"command": {
        "title": "PHPUnit LSP",
        "command": "/usr/local/bin/vagrant exec php",
        "arguments": [
            "/usr/bin/phpunit",
            "-c",
            "/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/phpunit.xml",
            "plugins/my-plugin/tests/test-class-endpoint.php"
        ]
    },
```

**Comment by nunoperalta** [comment]
Opened new issue https://github.com/recca0120/vscode-phpunit/issues/104 with the reason of the problem I was having above, on my second comment. The original issue above is resolved.
