### ISSUE TITLE
Only running first test

### ISSUE THREAD

**Issue by tyler36** [recca0120/vscode-phpunit#99]
I've been using TestExplorer with PHPUnit TestExplorer for quite a while and recently started using the "useNativeTesting" option.

As of 1.59.0 however, TestExplorer with only run the first test when I click the "Run all tests" button. I can run all tests in a file or an individual test by click on the button in the test tree. If I disable "useNativeTesting", I can run all tests.

I tried a portable VScode 1.58 and it worked. That's using a different version of TestAdapter and TestExplorer. Upgrading the install to 1.59 also updates the extentions.

It fails on the current VScode Insider 1.60 (2021-08-18) too.

OS: Win10
Vscode: 1.59.0
TestExplorer: 2.21.0
PHPUnit TestExplorer: 2.0.76
Test Adapter Converter: 0.1.2

I originally posted this in the `hbenl/vscode-test-explorer` support [#225](https://github.com/hbenl/vscode-test-explorer/issues/225) but they said this extension was the problem.

**Comment by madebycaliper** [comment]
@tyler36 I'm also experiencing the same problem on Mac with an identical version set of the extensions.

OS: Mac OS 10.14.6
VScode: 1.59.0
TestExplorer: 2.21.1
PHPUnit TestExplorer: 2.0.76
Test Adapter Converter: 0.1.2

Let me know if you discover a fix!

**Comment by tobiasbhn** [comment]
Same here. Still not fixed. Any news on this topic?

**Comment by recca0120** [comment]
I'm rewriting this extension now.

**Comment by recca0120** [comment]
try version 3.0.

**Comment by tyler36** [comment]
Version `3.0.2` appears to function correctly.

Thank you for the update.
